namespace: "comprasweb"
env: "prod"

comprasweb:
  replicaCount: 1
  image:
    repository: feliperibeiro95/lista-compras
    tag: "2.2.2"
  port: 3000
  serviceName: comprasweb
  dbaccess:
    usernamedb: ""
    passwordb: ""
    hostaddrdb: ""
    databasename: ""

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  ingressClassName: "nginx"
  rewriteTarget: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "compras2.felipeduribeiro.com.br"
      paths:
        - path: /
          pathType: Prefix
          service: comprasweb
          port: 3000
  tls:
    enabled: true
    config:
      - hosts:
          - "compras2.felipeduribeiro.com.br"
        secretName: comprasweb-cert
