apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.comprasweb.serviceName }}-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.comprasweb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.comprasweb.serviceName }}-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.comprasweb.serviceName | quote }}-{{ .Values.env }}
        version: {{ .Values.comprasweb.image.tag | quote }}
        web: "comprasweb"
    spec:
      containers:
        - name: {{ .Values.comprasweb.serviceName }}-{{ .Values.env }}
          image: "{{ .Values.comprasweb.image.repository }}:{{ .Values.comprasweb.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: "{{ .Values.comprasweb.image.tag }}"
          livenessProbe:
            exec:
              command: {{ .Values.comprasweb.livenessProbe.execCommand | toJson }}
            failureThreshold: {{ .Values.comprasweb.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.comprasweb.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.comprasweb.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.comprasweb.livenessProbe.timeoutSeconds }}
          ports:
            - containerPort: {{ .Values.comprasweb.port }}
              protocol: TCP
          env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: compras-db-secret-{{ .Values.env }}
                key: hostaddrdb
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: compras-db-secret-{{ .Values.env }}
                key: passwordb
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: compras-db-secret-{{ .Values.env }}
                key: databasename
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: compras-db-secret-{{ .Values.env }}
                key: usernamedb
