apiVersion: v1
kind: Secret
metadata:
  name: "compras-db-secret-{{ .Values.env }}"
  namespace: {{ .Values.namespace }}
data:
  usernamedb: {{ .Values.comprasweb.dbaccess.usernamedb | b64enc | quote }}
  passwordb: {{ .Values.comprasweb.dbaccess.passwordb | b64enc | quote }}
  hostaddrdb: {{ .Values.comprasweb.dbaccess.hostaddrdb | b64enc | quote }}
  databasename: {{ .Values.comprasweb.dbaccess.databasename| b64enc | quote }}