apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.comprasweb.serviceName }}-{{ .Values.env }}"
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.comprasweb.port }}
      targetPort: {{ .Values.comprasweb.port }}
  selector:
    app: {{ .Values.comprasweb.serviceName }}
  type: ClusterIP