name: Test Code

on:
  push:
    push:
      - 'main'
      - 'dev'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Image for application
      run: docker build -t my_app .

    - name: Start Mysql
      run: |
        docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -e MYSQL_DATABASE=${{ env.MYSQL_DATABASE }} -p 3306:3306 mysql:5.7

    - name: Start container App
      run: |
        docker run -d --name node-app -p 3000:3000 --link mysql:db my_app

    - name: Wait for MySQL to be ready
      run: |
        end=$(($(date +%s) + 60))
        until docker exec mysql mysql -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{ env.MYSQL_DATABASE }}"; do
          if [[ $(date +%s) -ge $end ]]; then
            echo "MySQL startup timed out."
            break
          fi
          echo "Waiting for MySQL to be up..."
          sleep 5
        done
    
    - name: Populate MySQL Database
      run: docker exec -i mysql mysql -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} < db/lista_compras.sql
      
    - name: Test application
      run: |
        sleep 10  # waiting for Node app to start up
        curl -s http://localhost:3000
    
    - name: Clean up
      if: always()
      run: docker stop node-app mysql