name: Test Code

on:
  push:
    push:
      - 'main'
      - 'dev'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Image for application
      run: docker build -t my_app .

    - name: Start Mysql
      run: |
        docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -e MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }} -p 3306:3306 mysql:5.7

    - name: Start container App
      run: |
        docker run -d --name node-app -p 3000:3000 -e MYSQL_USER=root -e MYSQL_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -e MYSQL_HOST=mysql -e MYSQL_DB=${{ vars.MYSQL_DATABASE }} --link mysql:db my_app

    - name: Wait for MySQL to be ready
      run: |
        end=$(($(date +%s) + 60))
        until docker exec mysql mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "select 1 from dual"; do
          if [[ $(date +%s) -ge $end ]]; then
            echo "Database creation timed out."
            break
          elif [[ $? == 0 ]]; then
            echo "Database created"
            break
          fi
          echo "Waiting for MySQL to be ready to create the database..."
          sleep 5
        done
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    #- name: Wait for MySQL to be ready
    #  run: docker exec mysql mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE ${MYSQL_DATABASE}";
    #  env:
    #    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    #    MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}

    - name: Import MySQL Database
      run: docker cp db/lista_compras.sql mysql:/tmp
    
    - name: Populate MySQL Database
      run: docker exec mysql mysql -uroot -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} < ./db/lista_compras.sql
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}

    - name: Test application
      run: curl -s http://localhost:3000
        
    - name: Get logs
      if: always()
      run: docker logs node-app
    
    - name: Clean up
      if: always()
      run: docker stop node-app mysql
